# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - develop
    - features/*
    - hotfixes/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: VersionAssemblies@2
  inputs:
    filePattern: '**/AssemblyInfo.*'
    versionSource: 'buildNumber'
    versionFormat: 'custom'
    customBuildRegex: '(\d{8})\.(\d+)'
    replaceVersionFormat: 'custom'
    customReplaceRegex: '\.\d\.\d"\)\]$'
    buildRegexIndex: '2'
    replacePrefix: '.'
    replacePostfix: '")]'
    failIfNoMatchFound: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    contents: '**\bin\$(buildConfiguration)\**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'